### ISSUE TITLE
Add support for Laravel 6

### ISSUE THREAD

**Issue by nabihnadhif** [graze/gigya-client#33]
Support for bug fixes for Laravel 5.8 ended on August 26, 2019. Security issues are still being maintained until February 26, 2020.

**Comment by mastommel** [comment]
PR: https://github.com/graze/gigya-client/pull/34

**Comment by mastommel** [comment]
@biggianteye Can you tag a new version so that the compatibility to current Laravel versions can be used after merging #34?
Would be great. Many thanks!

**Comment by biggianteye** [comment]
Done.
