### ISSUE TITLE
Wrong exception classes

### ISSUE THREAD

**Issue by adragus-inviqa** [graze/gigya-client#6]
Both files extend a non-existent class (`Mockery\Exception`) so they'll fail when thrown:
- https://github.com/graze/gigya-client/blob/297cec85ca00aa4120d1343355bfc34cdaf489ea/src/Exceptions/InvalidFriendUidSignatureException.php
- https://github.com/graze/gigya-client/blob/297cec85ca00aa4120d1343355bfc34cdaf489ea/src/Exceptions/InvalidUidSignatureException.php

**Comment by wpillar** [comment]
Is this not the exception they are extending? https://github.com/padraic/mockery/blob/master/library/Mockery/Exception.php

**Comment by h-bragg** [comment]
They are meant to be standard Exception. Guess I grabbed the wrong one from the Resolve Uses.
