### ISSUE TITLE
Date format and parsing problems

### ISSUE THREAD

**Issue by adragus-inviqa** [graze/gigya-client#7]
### Problem 1: ###
Gigya returns the `time` property of a response as being "represented in ISO 8601 format. i.e., yyyy.mm.dd.Thh.MM.ss.**SSS**Z". Note the microseconds (`SSS`).

But for other time attributes, like `registered`, they say they return "in ISO 8601 format, e.g. '1997-07-16T19:20:30Z'"; so no microseconds. But from my research, they do actually return with microseconds. This is a documentation fault on their part and they should be notified about it.

Every time-related attribute coming from Gigya has the `yyyy.mm.dd.Thh.MM.ss.SSSZ` format, from what I could gather.

The difference between returning with microseconds and without them, unfortunately, is important, because:

### Problem 2: ###
`DateTime(Immutable)::createFromFormat()` doesn't correctly parse date strings in the `yyyy.mm.dd.Thh.MM.ss.SSSZ` format, what is this, I don't even... :trollface: 

PHP.net comment: http://php.net/manual/en/class.datetime.php#108970

So `$this->time` is always false:
https://github.com/graze/gigya-client/blob/297cec85ca00aa4120d1343355bfc34cdaf489ea/src/Response/Response.php#L73
```
$ php -v
PHP 5.6.12 (cli) (built: Aug  7 2015 11:29:31)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

php > var_dump(DateTimeImmutable::createFromFormat(DateTime::ATOM, '2015-10-04T10:46:24.311Z'));
bool(false)

php > var_dump(DateTimeImmutable::createFromFormat(DateTime::ATOM, '2015-10-04T10:46:24Z'));
class DateTimeImmutable#1 (3) {
  public $date =>
  string(26) "2015-10-04 10:46:24.000000"
  public $timezone_type =>
  int(2)
  public $timezone =>
  string(1) "Z"
}
```
Note that it fails when the date string contains microseconds - `'2015-10-04T10:46:24.311Z'` vs `2015-10-04T10:46:24Z`.

----

I think we'd better use our own custom format instead of directly using `ATOM`. Haven't tried it yet, though.
I leave the decision to you, as I don't see us using that `time` attribute any time soon.

**Comment by h-bragg** [comment]
Resolved this, but build failing due to hhvm bug.
